### PR TITLE
fix(apollo-link): fix infinite loop while refreshing the session

### LINKED ISSUE #839: [@accounts/apollo-link] accountsClient.refreshSession() causes infinite loop
This is tough one to debug. When using `authLink` I'm getting infinite loops and browser tab crashing after stopping and resuming my dev server.

I'm using authLink like this

```
const authLink = accountsLink(() => accountsClient)
const httpLink = new HttpLink({
  uri: '/graphql',
})

const cache = new InMemoryCache()
const client = new ApolloClient({
  link: from([authLink, httpLink]),
  cache,
  resolvers,
})
```

I'm not getting anything from the browser's profiler because it crashes out. If I comment out the authLink, the client loads, re-add it and everything works as expected until I stop and restart my dev server.

No errors or anything odd present on the server. 

Any thoughts here? Has only started happening since adding the authLink, but I honestly have no clue on the cause here. Any ideas on the best way to troubleshoot this?

### PR DESCRIPTION
**Pull request by pradel**
Close #839

### CODE REVIEW

File: packages/apollo-link-accounts/src/index.ts [hunk 1]
```diff
@@ -5,14 +5,19 @@ import { AccountsClient } from '@accounts/client';
...
-
     const headers = { ...headersWithoutTokens };
 
-    if (tokens) {
-      headers.Authorization = 'Bearer ' + tokens.accessToken;
+    /**
+     * We have to check this condition to avoid an infinite loop
+     * during the refresh token operation
+     */
+    if (req.operationName !== 'refreshTokens') {
```
Comment (thomasttvo) [inline packages/apollo-link-accounts/src/index.ts]: @pradel isn't 'refreshTokens' a string constant? is there anyway we can use that constant instead of using a raw value here?

Comment (thomasttvo) [reply packages/apollo-link-accounts/src/index.ts]: (I know you merge the PR, but I thought I should point out this one)

Comment (pradel) [reply packages/apollo-link-accounts/src/index.ts]: @thomasttvo that's a good idea since it's a constant, but I am not sure how to achieve that in the current setup 😁
